Evento/urls.py
from django.urls import path
from .import views


app_name = "Evento"

urlpatterns = [
	path("consultar_eventos/<cat_id>", views.consultar_eventos, name="consultar_eventos"),
	path("consultar_eventos_all", views.consultar_eventos_all, name="consultar_eventos_all"),
    path("consultar_eventos_proponente_all", views.consultar_eventos_proponente_all, name="consultar_eventos_proponente_all"),
    path("consultar_eventos_validados_all", views.consultar_eventos_validados_all, name="consultar_eventos_validados_all"),
    path("consultar_eventos_proponente/<cat_id>", views.consultar_eventos_proponente, name="consultar_eventos_proponente"),
    path("consultar_eventos_validados/<cat_id>", views.consultar_eventos_validados, name="consultar_eventos_validados"),

	path("visualizar_evento/<evento_id>", views.visualizar_evento, name="visualizar_evento"),

    path("criar_evento", views.criar_evento, name="criar_evento"),

	path("cancelar_evento/<evento_id>", views.cancelar_evento, name="cancelar_evento"),

	path("editar_evento/<evento_id>", views.editar_evento, name="editar_evento"),

    path("submeter_evento/<evento_id>", views.submeter_evento, name="submeter_evento"),
    path("validar_evento/<evento_id>", views.validar_evento, name="validar_evento"),

    path("criar_logistica/<evento_id>", views.criar_logistica, name="criar_logistica"),

    path("visualizar_logistica/<evento_id>", views.visualizar_logistica, name="visualizar_logistica"),

    path("editar_logistica/<logistica_id>", views.editar_logistica, name="editar_logistica"),

    path("cancelar_logistica/<logistica_id>", views.cancelar_logistica, name="cancelar_logistica"),

    path("submeter_logistica/<logistica_id>", views.submeter_logistica, name="submeter_logistica"),
    path("validar_logistica/<logistica_id>", views.validar_logistica, name="validar_logistica"),
    
    path("atribuir_sala/<evento_id>", views.atribuir_sala, name="atribuir_sala"),
    path("atribuir_equipamento/<evento_id>", views.atribuir_equipamento, name="atribuir_equipamento"),
    path("atribuir_serviço/<evento_id>", views.atribuir_serviço, name="atribuir_serviço"),
    
    path("cancelar_atribuir_sala/<removeid>", views.cancelar_atribuiçao_sala, name="cancelar_atribuir_sala"),
    path("cancelar_atribuir_equipamento/<removeid>", views.cancelar_atribuiçao_equipamento, name="cancelar_atribuir_equipamento"),
    path("cancelar_atribuir_serviço/<removeid>", views.cancelar_atribuiçao_serviço, name="cancelar_atribuir_serviço"),
]

Formulario/urls.py
from django.urls import path
from . import views
app_name = "Formulario"

urlpatterns = [
    path("consultar_perguntas/<id>/<formulario_id>", views.consultar_perguntas, name="consultar_perguntas"),
    path("add_pergunta/<formulario_id>", views.add_pergunta, name="add_pergunta"),
    path("add_opcao_resposta/<pergunta_id>/<formulario_id>", views.add_opcao_resposta, name="add_opcao_resposta"),
    path("remover_perguntas/<pergunta_id>/<formulario_id>", views.remover_pergunta, name="remover_pergunta"),
    path("delete_resposta/<pergunta_id>/<resposta_id>/<formulario_id>", views.delete_resposta, name="delete_resposta"),
    path("editar_pergunta/<pergunta_id>/<formulario_id>", views.editar_pergunta, name="editar_pergunta"),
    path("editar_opcao_resposta/<pergunta_id>/<resposta_id>/<formulario_id>", views.editar_opcao_resposta, name="editar_opcao_resposta"),
    
    path("consultar_formularios/<evento_id>", views.consultar_formularios, name="consultar_formularios"),
    path("consultar_formularios_special", views.consultar_formularios_special, name="consultar_formularios_special"),
    
    path("add_formulario/<evento_id>", views.add_formulario, name="add_formulario"),
    path("add_formulario_special", views.add_formulario_special, name="add_formulario_special"),

    path("add_pergunta_ao_formulario/<formulario_id>", views.add_pergunta_ao_formulario, name="add_pergunta_ao_formulario"),
    path("editar_formulario/<formulario_id>", views.editar_formulario, name="editar_formulario"),
    path("editar_formulario_special/<formulario_id>", views.editar_formulario_special, name="editar_formulario_special"),
    path("eliminar_formulario/<formulario_id>", views.eliminar_formulario, name="eliminar_formulario"),
    path("alterar_estado_formulario/<formulario_id>", views.alterar_estado_formulario, name="alterar_estado_formulario"),
    path("add_pergunta_ao_formulario_action/<pergunta_id>/<formulario_id>", views.add_pergunta_ao_formulario_action, name="add_pergunta_ao_formulario_action"),
    path("pergunta_move_up/<pergunta_id>/<formulario_id>", views.pergunta_move_up, name="pergunta_move_up"),
    path("pergunta_move_down/<pergunta_id>/<formulario_id>", views.pergunta_move_down, name="pergunta_move_down"),

    path("remover_pergunta_do_formulario/<pergunta_id>/<formulario_id>", views.remover_pergunta_do_formulario, name="remover_pergunta_do_formulario"),
    path("editar_pergunta_do_formulario/<pergunta_id>/<formulario_id>", views.editar_pergunta_do_formulario, name="editar_pergunta_do_formulario"),
    
]

LES/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = "LES"

urlpatterns = [
    #Ricardo
    path('Formulario/', include('Formulario.urls')),

    #Filipe
    path('Evento/', include('Evento.urls')),
    #Guilherme
    path('Inscricao/', include('Inscriçao.urls')),
    #Dario
    path('Recurso/', include('Recurso.urls')),

    path('admin/', admin.site.urls),

    path('Utilizadores/', include('Utilizadores.urls')),

    path('', views.home, name='home'),
]

Formulario/models.py
from django.db import models

class Formulário(models.Model):
    id = models.AutoField(db_column='ID', primary_key=True)
    tipo_de_eventoid = models.ForeignKey('Evento.TipoDeEvento', models.SET_NULL, default=None, null=True, blank=True, db_column='Tipo de eventoID')  # Field name made lowercase. Field renamed to remove unsuitable characters.
    tipo_de_formulárioid = models.ForeignKey('TipoDeFormulário', models.SET_NULL, default=None, null=True, db_column='Tipo de FormulárioID')  # Field name made lowercase. Field renamed to remove unsuitable characters.
    nome = models.CharField(db_column='Nome', max_length=255, blank=True, null=True)
    publico = models.BooleanField(db_column='Publico')
    evento_id = models.ForeignKey('Evento.Evento', models.SET_NULL, default=None, null=True, blank=True, db_column='Evento')

    class Meta:
        managed = True
        db_table = 'Formulário'


class FormulárioPergunta(models.Model):
    id = models.AutoField(db_column='ID', primary_key=True)
    formulárioid = models.ForeignKey('Formulário' , on_delete=models.CASCADE, db_column='FormulárioID')
    perguntaid = models.ForeignKey('Pergunta', on_delete=models.CASCADE, db_column='PerguntaID')
    pos = models.IntegerField(models.SET_NULL, default=None, null=True, db_column='Pos')

    class Meta:
        managed = True
        db_table = 'Formulário_Pergunta'


class OpçãoDeResposta(models.Model):
    id = models.AutoField(db_column='ID', primary_key=True)
    perguntaid = models.ForeignKey('Pergunta', models.CASCADE, default=None, null=True, db_column='PerguntaID')
    opção = models.CharField(db_column='Opção', max_length=255, blank=True, null=True)

    class Meta:
        managed = True
        db_table = 'Opção de resposta'

    def __str__(self):
        return str(self.opção)

class Pergunta(models.Model):
    id = models.AutoField(db_column='ID', primary_key=True)
    pergunta = models.CharField(db_column='Pergunta', max_length=255, blank=True, null=True)
    obrigatório = models.BooleanField(db_column='Obrigatório')
    tipo_de_perguntaid = models.ForeignKey('TipoDePergunta', models.SET_NULL, default=None, null=True, db_column='Tipo de perguntaID')
    numero_maximo_de_escolhas = models.IntegerField(db_column='NumeroMaximoDeEscolhas', default =None, null=True)
    temporario = models.BooleanField(default=False, db_column='temporario')

    class Meta:
        managed = True
        db_table = 'Pergunta'

    def __str__(self):
        return str(self.pergunta)


class Resposta(models.Model):
    id = models.AutoField(db_column='ID', primary_key=True)  # Field name made lowercase.
    perguntaid = models.ForeignKey('Formulario.Pergunta', models.SET_NULL, default=None, null=True, db_column='PerguntaID')  # Field name made lowercase.
    eventoid = models.ForeignKey('Evento.Evento', models.SET_NULL, default=None, null=True, db_column='EventoID')  # Field name made lowercase.
    inscriçãoid = models.ForeignKey('Inscriçao.Inscrição', models.SET_NULL, default=None, null=True, db_column='InscriçãoID')  # Field name made lowercase.
    feedbackid = models.ForeignKey('Inscriçao.Feedback', models.SET_NULL, default=None, null=True, db_column='FeedbackID')  # Field name made lowercase.
    resposta = models.CharField(db_column='Resposta', max_length=2048, blank=True, null=True)  # Field name made lowercase.

    class Meta:
        managed = True
        db_table = 'Resposta'


class TipoDeFormulário(models.Model):
    id = models.AutoField(db_column='ID', primary_key=True)  # Field name made lowercase.
    nome = models.CharField(db_column='Nome', max_length=255, blank=True, null=True)  # Field name made lowercase.

    class Meta:
        managed = True
        db_table = 'Tipo de Formulário'

    def __str__(self):
        return str(self.nome)


class TipoDePergunta(models.Model):
    id = models.AutoField(db_column='ID', primary_key=True)  # Field name made lowercase.
    nome = models.CharField(db_column='Nome', max_length=255, blank=True, null=True)  # Field name made lowercase.

    class Meta:
        managed = True
        db_table = 'Tipo de pergunta'
        
    def __str__(self):
        return str(self.nome)

Formulario/forms.py
from django import forms
from django.forms import ModelForm, fields, widgets
from .models import *
from django.shortcuts import get_object_or_404

class pergunta_form(ModelForm):
    class Meta:
        model = Pergunta
        fields = (
            'pergunta',
            'obrigatório',
            'tipo_de_perguntaid'
        )

        labels = {
            'tipo_de_perguntaid': ('Tipo de pergunta')
        }

        widgets = {
			'pergunta' : forms.TextInput(attrs={'class' : 'form-control'}),
            'tipo_de_perguntaid' : forms.Select(attrs={'class' : 'form-control'}),
		}


class opcao_resposta_form(ModelForm):
    class Meta:
        model = OpçãoDeResposta
        fields = (
            'opção',
        )

        labels = {
            'opção': ('Resposta'),
        }

        widgets = {
			'opção' : forms.TextInput(attrs={'class' : 'form-control'}),
		}
        
class novo_formulario_form(ModelForm):

    class Meta:
        model = Formulário
        tipo_de_eventoid = forms.CharField(required=True)
        fields = (
            'nome',
            'tipo_de_formulárioid',
            'tipo_de_eventoid',
        )
        labels = {
            'tipo_de_formulárioid': ('Tipo de formulário'),
            'tipo_de_eventoid': ('Tipo de evento'),
        }

        widgets = {
			'nome' : forms.TextInput(attrs={'class' : 'form-control'}),
            'tipo_de_formulárioid' : forms.Select(attrs={'class' : 'form-control'}),
            'tipo_de_eventoid' : forms.Select(attrs={'class' : 'form-control'}),
		}

class novo_formulario_2_form(ModelForm):

    class Meta:
        model = Formulário
        tipo_de_eventoid = forms.CharField(required=True)
        fields = (
            'nome',
            'tipo_de_eventoid',
        )
        labels = {
            'tipo_de_eventoid': ('Tipo de evento'),
        }

        widgets = {
			'nome' : forms.TextInput(attrs={'class' : 'form-control'}),
            'tipo_de_eventoid' : forms.Select(attrs={'class' : 'form-control'}),
		}

Formulario/templates/add_opcao_resposta.html
{% extends 'app.html' %}

{% block title %}- Adicionar Formulário {% endblock title %}

{% block content %}
{% load static %}
	<div class="center">
		<h1>Adicionar opções de resposta</h1>
		<br>
		<div class="container-fluid">
			<h3>{{ pergunta }}</h3>
		</div>
		<br>
		<ul>
			{% for r in respostas %}
			<li>{{r}}
				<a href="{% url 'Formulario:delete_resposta' pergunta.id r.id formulario_id %}">Eliminar</a>
				<a> | </a>
				<a href="{% url 'Formulario:editar_opcao_resposta' pergunta.id r.id formulario_id %}">Editar</a>
			</li>
			{% endfor %}
		</ul>
		<br>
		<div class="container">
			<form action="" method=POST>
				{% csrf_token %}
				{{ form.as_p }}

				<br><br>
				<input type="submit" value="Submit" class="btn btn-success">
				{% if state == True %}
				<a href="{% url 'Formulario:add_pergunta_ao_formulario' formulario_id %}"><button type="button"
					class="btn btn-primary">Voltar</button></a>
				{% else %}
				{% if formulario_id == "None" %}
				<a href="{% url 'Formulario:consultar_perguntas' 0 formulario_id %}"><button type="button"
						class="btn btn-primary">Voltar</button></a>
				{% else %}
				<a href="{% url 'Formulario:consultar_perguntas' 1 formulario_id %}"><button type="button"
						class="btn btn-primary">Voltar</button></a>
				{% endif %}
				{% endif %}



			</form>
		</div>
	</div>
{% endblock content %}

Formulario/templates/add_pergunta_ao_formulario.html
{% extends 'app.html' %}

{% block title %}- Adicionar Perguntas ao Formulário {% endblock title %}

{% block content %}
{% load static %}
		<div class="container-fluid">
			<div class="center"> 
				<h1>Perguntas do Formulário "{{formulario.nome}}"</h1>
			</div>
			<br>
			<a href="{% url 'Formulario:consultar_perguntas' 1 formulario.id %}">
				<button type="button" class="btn btn-primary">Adicionar perguntas</button>
			</a>
			{% if formulario.tipo_de_formulárioid.nome != 'Proposta de evento' %}
				<a href="{% url 'Formulario:consultar_formularios' evento_id%}">
					<button type="button" class="btn btn-primary" >Voltar</button>
				</a>
			{% else %}
				<a href="{% url 'Formulario:consultar_formularios_special'%}">
					<button type="button" class="btn btn-primary" >Voltar</button>
				</a>
			{% endif %}
			<br><br>
			<table class = "table">
				<tr>
					<th>#</th>
					<th>Pergunta</th>
					<th>Tipo de Pergunta</th>
					<th>Respostas:</th>
					<th>Opções</th>
				</tr>
				{% for p in perguntas %}
				<tr>
					<td>{{p.pos}}
						{% if p.pos != 1 %}
						<a href="{% url 'Formulario:pergunta_move_up' p.perguntaid.id formulario.id %}">
							<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-chevron-up" viewBox="0 0 16 16"><path fill-rule="evenodd" d="M7.646 4.646a.5.5 0 0 1 .708 0l6 6a.5.5 0 0 1-.708.708L8 5.707l-5.646 5.647a.5.5 0 0 1-.708-.708l6-6z"/></svg>
						</a>
						{% endif %}
						{% if p.pos != count %}
						<a href="{% url 'Formulario:pergunta_move_down' p.perguntaid.id formulario.id %}">
							<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-chevron-down" viewBox="0 0 16 16"><path fill-rule="evenodd" d="M1.646 4.646a.5.5 0 0 1 .708 0L8 10.293l5.646-5.647a.5.5 0 0 1 .708.708l-6 6a.5.5 0 0 1-.708 0l-6-6a.5.5 0 0 1 0-.708z"/></svg>
						</a>
						{% endif %}
					</td>
					<td>{{p.perguntaid.pergunta}}</td>
					<td>{{p.perguntaid.tipo_de_perguntaid.nome}}</td>
					<td class="dropdown">
						{% if p.perguntaid.tipo_de_perguntaid.id == 1 %}
						<button class="btn btn-primary dropdown-toggle" type="button" data-toggle="dropdown">Ver
							respostas
							<span class="caret"></span></button>
						<ul class="dropdown-menu">
							{% for or in OpcaoResposta %}
								{% if or.perguntaid == p.perguntaid %}
									<li><a>{{or}}</a></li>
								{% endif %}
							{% endfor %}
						</ul>
						{% else %}
							<p>----</p>
						{% endif %}
					</td>
					<td>
						<a href="{% url 'Formulario:editar_pergunta_do_formulario' p.perguntaid.id formulario.id %}" class="card-link">Editar</a>
						<a> | </a>
						<a href="{% url 'Formulario:remover_pergunta_do_formulario' p.perguntaid.id formulario.id %}" class="card-link" onclick="clicked(event)">
							<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash" viewBox="0 0 16 16">
								<path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z"/>
								<path fill-rule="evenodd" d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z"/>
							</svg>
						</a>
					</td>
				</tr>
				{% endfor %}
			</table>
		</div>
		<script>
			function clicked(e)
			{
				if(!confirm('Tem a certeza que pretende retirar esta pergunta deste formulário')) {
					e.preventDefault();
				}
			}
			</script>
{% endblock content %}

Formulario/templates/consultar_formularios.html
{% extends 'app.html' %}

{% block title %}- Consultar Formulários {% endblock title %}

{% block content %}
{% load static %}
  <div class="container-fluid">
    {% if state == 'evento' %}
    <div class="center">
      <h1>Formulários do evento {{evento.nome}}</h1>
    </div>
    <br>
      <a href="{% url 'Formulario:add_formulario' evento.id %}"><button type="button" class="btn btn-primary">Add Formulário</button></a>
      <a href="{% url 'Evento:consultar_eventos_all' %}"><button type="button" class="btn btn-primary">Voltar</button></a>
    {% else %} 
    <div class="center">
      <h1>Formulários de proposta de evento</h1>
    </div>
    <br>
      <a href="{% url 'Formulario:add_formulario_special' %}"><button type="button" class="btn btn-primary">Add Formulário Proposta Evento</button></a>
    {% endif %}

    <br><br>
    <table class="table">
      <tr>
        <th>Nome</th>
        <th>Tipo de Formulário</th>
        <th>Tipo de Evento</th>
        <th>Estado</th>
        <th>Opção</th>
      </tr>
      {% for f in Formulario %}
      <tr>
        <td>{{f.nome}}</td>
        <td>{{f.tipo_de_formulárioid}}</td>
        <td>
          {% if f.tipo_de_eventoid == None %}
            -----
          {% else %}
            {{f.tipo_de_eventoid}}
          {% endif %}  
        </td>
        <td>
          {% if f.publico == True %}
            Publico
          {% else %}
            Não está Publico
          {% endif %}
        </td>
        <td>
          {% if f.evento_id %}
            <a href="{% url 'Formulario:editar_formulario' f.id %}" class="card-link"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pencil" viewBox="0 0 16 16">
              <path d="M12.146.146a.5.5 0 0 1 .708 0l3 3a.5.5 0 0 1 0 .708l-10 10a.5.5 0 0 1-.168.11l-5 2a.5.5 0 0 1-.65-.65l2-5a.5.5 0 0 1 .11-.168l10-10zM11.207 2.5 13.5 4.793 14.793 3.5 12.5 1.207 11.207 2.5zm1.586 3L10.5 3.207 4 9.707V10h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.293l6.5-6.5zm-9.761 5.175-.106.106-1.528 3.821 3.821-1.528.106-.106A.5.5 0 0 1 5 12.5V12h-.5a.5.5 0 0 1-.5-.5V11h-.5a.5.5 0 0 1-.468-.325z"/>
              </svg></a>
          {% else %}
            <a href="{% url 'Formulario:editar_formulario_special' f.id %}" class="card-link"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pencil" viewBox="0 0 16 16">
              <path d="M12.146.146a.5.5 0 0 1 .708 0l3 3a.5.5 0 0 1 0 .708l-10 10a.5.5 0 0 1-.168.11l-5 2a.5.5 0 0 1-.65-.65l2-5a.5.5 0 0 1 .11-.168l10-10zM11.207 2.5 13.5 4.793 14.793 3.5 12.5 1.207 11.207 2.5zm1.586 3L10.5 3.207 4 9.707V10h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.293l6.5-6.5zm-9.761 5.175-.106.106-1.528 3.821 3.821-1.528.106-.106A.5.5 0 0 1 5 12.5V12h-.5a.5.5 0 0 1-.5-.5V11h-.5a.5.5 0 0 1-.468-.325z"/>
              </svg></a>
          {% endif %}
          <a> | </a>
          <a href="{% url 'Formulario:eliminar_formulario' f.id %}" class="card-link" onclick="clicked(event)">
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash" viewBox="0 0 16 16">
              <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z"/>
              <path fill-rule="evenodd" d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z"/>
            </svg>
          </a>
          <a> | </a>
          <a href="{% url 'Formulario:alterar_estado_formulario' f.id %}" class="card-link">Alterar estado</a>
        </td>
      </tr>
      {% endfor %}
    </table>
  </div>
<script>
  function clicked(e)
  {
      if(!confirm('Tem a certeza que pretende eliminar este formulário?')) {
          e.preventDefault();
      }
  }
  </script>
{% endblock content %}

Formulario/templates/consultar_perguntas.html
{% extends 'app.html' %}

{% block title %}- Adicionar Formulário {% endblock title %}

{% block content %}
{% load static %}
  <div class="container-fluid">
    <div class="center">
      <h1>Perguntas</h1>
    </div>
    <br>  
      <a href="{% url 'Formulario:add_pergunta' formulario_id %}"><button type="button" class="btn btn-primary">Criar nova pergunta</button></a>
      {% if id == '1' %}
      <a href="{% url 'Formulario:add_pergunta_ao_formulario' formulario_id %}"><button type="button" class="btn btn-primary">Voltar</button></a>
      {% endif %}
    <br><br>
    <table class = "table">
      <tr>
        <th>Pergunta</th>
        <th>Tipo de Pergunta</th>
        <th>Respostas:</th>
        {% if id == '1' %}
          <th>Adicionar</th>
        {% else %}
          <th>Opções</th>
        {% endif %}
      </tr>
      {% for p in Pergunta %}
      <tr>
        <td>{{p.pergunta}}</td>
        <td>{{p.tipo_de_perguntaid.nome}}</td>
        <td class="dropdown">
          {% if p.tipo_de_perguntaid.id == 1 %}
          <button class="btn btn-primary dropdown-toggle" type="button" data-toggle="dropdown">Ver respostas
            <span class="caret"></span></button>
          <ul class="dropdown-menu">
            {% for or in OpcaoResposta %}
              {% if or.perguntaid == p %}
                <li><a>{{or}}</a></li>
              {% endif %}
            {% endfor %}
          </ul>
          {% else %}
            <p>----</p>
          {% endif %}
        </td>
        <td>
          {% if id == '1' %}
            <a href="{% url 'Formulario:add_pergunta_ao_formulario_action' p.id formulario_id %}" class="card-link">Adicionar</a>
            <a> | </a>
          {% endif %}
          <a href="{% url 'Formulario:editar_pergunta' p.id formulario_id %}" class="card-link"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pencil" viewBox="0 0 16 16">
            <path d="M12.146.146a.5.5 0 0 1 .708 0l3 3a.5.5 0 0 1 0 .708l-10 10a.5.5 0 0 1-.168.11l-5 2a.5.5 0 0 1-.65-.65l2-5a.5.5 0 0 1 .11-.168l10-10zM11.207 2.5 13.5 4.793 14.793 3.5 12.5 1.207 11.207 2.5zm1.586 3L10.5 3.207 4 9.707V10h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.293l6.5-6.5zm-9.761 5.175-.106.106-1.528 3.821 3.821-1.528.106-.106A.5.5 0 0 1 5 12.5V12h-.5a.5.5 0 0 1-.5-.5V11h-.5a.5.5 0 0 1-.468-.325z"/>
            </svg></a>
          <a> | </a>
          <a href="{% url 'Formulario:remover_pergunta' p.id formulario_id %}" class="card-link" onclick="clicked(event)">
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash" viewBox="0 0 16 16">
              <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z"/>
              <path fill-rule="evenodd" d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z"/>
            </svg>
          </a>  
        </td>
      </tr>
      {% endfor %}
    </table>
  </div>
  <script>
    function clicked(e)
    {
        if(!confirm('Tem a certeza que pretende eliminar esta pergunta?')) {
            e.preventDefault();
        }
    }
    </script>
	{% endblock content %}