Evento/urls.py
from django.urls import path
from .import views


app_name = "Evento"

urlpatterns = [
	path("consultar_eventos/<cat_id>", views.consultar_eventos, name="consultar_eventos"),
	path("consultar_eventos_all", views.consultar_eventos_all, name="consultar_eventos_all"),
    path("consultar_eventos_proponente_all", views.consultar_eventos_proponente_all, name="consultar_eventos_proponente_all"),
    path("consultar_eventos_validados_all", views.consultar_eventos_validados_all, name="consultar_eventos_validados_all"),
    path("consultar_eventos_proponente/<cat_id>", views.consultar_eventos_proponente, name="consultar_eventos_proponente"),
    path("consultar_eventos_validados/<cat_id>", views.consultar_eventos_validados, name="consultar_eventos_validados"),

	path("visualizar_evento/<evento_id>", views.visualizar_evento, name="visualizar_evento"),

    path("criar_evento", views.criar_evento, name="criar_evento"),

	path("cancelar_evento/<evento_id>", views.cancelar_evento, name="cancelar_evento"),

	path("editar_evento/<evento_id>", views.editar_evento, name="editar_evento"),

    path("submeter_evento/<evento_id>", views.submeter_evento, name="submeter_evento"),
    path("validar_evento/<evento_id>", views.validar_evento, name="validar_evento"),

    path("criar_logistica/<evento_id>", views.criar_logistica, name="criar_logistica"),

    path("visualizar_logistica/<evento_id>", views.visualizar_logistica, name="visualizar_logistica"),

    path("editar_logistica/<logistica_id>", views.editar_logistica, name="editar_logistica"),

    path("cancelar_logistica/<logistica_id>", views.cancelar_logistica, name="cancelar_logistica"),

    path("submeter_logistica/<logistica_id>", views.submeter_logistica, name="submeter_logistica"),
    path("validar_logistica/<logistica_id>", views.validar_logistica, name="validar_logistica"),
    
    path("atribuir_sala/<evento_id>", views.atribuir_sala, name="atribuir_sala"),
    path("atribuir_equipamento/<evento_id>", views.atribuir_equipamento, name="atribuir_equipamento"),
    path("atribuir_serviço/<evento_id>", views.atribuir_serviço, name="atribuir_serviço"),
    
    path("cancelar_atribuir_sala/<removeid>", views.cancelar_atribuiçao_sala, name="cancelar_atribuir_sala"),
    path("cancelar_atribuir_equipamento/<removeid>", views.cancelar_atribuiçao_equipamento, name="cancelar_atribuir_equipamento"),
    path("cancelar_atribuir_serviço/<removeid>", views.cancelar_atribuiçao_serviço, name="cancelar_atribuir_serviço"),
]

Formulario/urls.py
from django.urls import path
from . import views
app_name = "Formulario"

urlpatterns = [
    path("consultar_perguntas/<id>/<formulario_id>", views.consultar_perguntas, name="consultar_perguntas"),
    path("add_pergunta/<formulario_id>", views.add_pergunta, name="add_pergunta"),
    path("add_opcao_resposta/<pergunta_id>/<formulario_id>", views.add_opcao_resposta, name="add_opcao_resposta"),
    path("remover_perguntas/<pergunta_id>/<formulario_id>", views.remover_pergunta, name="remover_pergunta"),
    path("delete_resposta/<pergunta_id>/<resposta_id>/<formulario_id>", views.delete_resposta, name="delete_resposta"),
    path("editar_pergunta/<pergunta_id>/<formulario_id>", views.editar_pergunta, name="editar_pergunta"),
    path("editar_opcao_resposta/<pergunta_id>/<resposta_id>/<formulario_id>", views.editar_opcao_resposta, name="editar_opcao_resposta"),
    
    path("consultar_formularios/<evento_id>", views.consultar_formularios, name="consultar_formularios"),
    path("consultar_formularios_special", views.consultar_formularios_special, name="consultar_formularios_special"),
    
    path("add_formulario/<evento_id>", views.add_formulario, name="add_formulario"),
    path("add_formulario_special", views.add_formulario_special, name="add_formulario_special"),

    path("add_pergunta_ao_formulario/<formulario_id>", views.add_pergunta_ao_formulario, name="add_pergunta_ao_formulario"),
    path("editar_formulario/<formulario_id>", views.editar_formulario, name="editar_formulario"),
    path("editar_formulario_special/<formulario_id>", views.editar_formulario_special, name="editar_formulario_special"),
    path("eliminar_formulario/<formulario_id>", views.eliminar_formulario, name="eliminar_formulario"),
    path("alterar_estado_formulario/<formulario_id>", views.alterar_estado_formulario, name="alterar_estado_formulario"),
    path("add_pergunta_ao_formulario_action/<pergunta_id>/<formulario_id>", views.add_pergunta_ao_formulario_action, name="add_pergunta_ao_formulario_action"),
    path("pergunta_move_up/<pergunta_id>/<formulario_id>", views.pergunta_move_up, name="pergunta_move_up"),
    path("pergunta_move_down/<pergunta_id>/<formulario_id>", views.pergunta_move_down, name="pergunta_move_down"),

    path("remover_pergunta_do_formulario/<pergunta_id>/<formulario_id>", views.remover_pergunta_do_formulario, name="remover_pergunta_do_formulario"),
    path("editar_pergunta_do_formulario/<pergunta_id>/<formulario_id>", views.editar_pergunta_do_formulario, name="editar_pergunta_do_formulario"),
    
]

Inscriçao/urls.py
from django.urls import path
from . import views

app_name = "Inscriçao"

urlpatterns = [
    # DEFAULT PATH
    path("", views.consultar_inscricoes_all, name="consultar_inscricoes"),
       
    # Consultar inscrições
    path(
        "consultar_user/<user_id>",
        views.consultar_inscricoes_user,
        name="consultar_inscricoes_user",
    ),
    path(
        "consultar_evento/<evento_id>",
        views.consultar_inscricoes_evento,
        name="consultar_inscricoes_evento",
    ),
    path(
        "consultar_all",
        views.consultar_inscricoes_all,
        name="consultar_inscricoes_all",
    ),

    # Consultar inscrição
    path(
        "consultar/<inscricao_id>",
        views.consultar,
        name="consultar",
    ),
    # Editar inscrição
    path(
        "editar/<inscricao_id>",
        views.editar,
        name="editar",
    ),
    # Criar Inscrição
    path(
        "criar/<evento_id>",
        views.criar,
        name="criar",
    ),
    # Remover Inscrição
    path(
        "remover/<inscricao_id>",
        views.remover,
        name="remover",
    ),
    # Validar Inscrição
    path(
        "validar/<inscricao_id>",
        views.validar,
        name="validar",
    ),
    # Checkin Inscrição
    path(
        "checkin/<evento_id>",
        views.checkin,
        name="checkin",
    ),

]

LES/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = "LES"

urlpatterns = [
    #Ricardo
    path('Formulario/', include('Formulario.urls')),

    #Filipe
    path('Evento/', include('Evento.urls')),
    #Guilherme
    path('Inscricao/', include('Inscriçao.urls')),
    #Dario
    path('Recurso/', include('Recurso.urls')),

    path('admin/', admin.site.urls),

    path('Utilizadores/', include('Utilizadores.urls')),

    path('', views.home, name='home'),
]

Recurso/urls.py
from django.urls import path
from . import views
app_name = "Recurso"

urlpatterns = [
        path("consultar_salas", views.consultar_salas, name="consultar_salas"),
        path("adicionar_salas", views.adicionar_salas, name="adicionar_salas_view"),
        path("cancelar_salas/<removeid>", views.cancelar_salas, name="remover_salas_view"),
        path("omitir_salas/<omitirid>", views.omitir_salas, name="omitir_salas_view"),
        path("alterar_salas/<alterarid>", views.alterar_salas, name="alterar_salas_view"),
        #=================================================================================
        path("consultar_serviços", views.consultar_serviços, name="consultar_serviços"),
        path("adicionar_serviços", views.adicionar_serviços, name="adicionar_serviços_view"),
        path("cancelar_serviços/<removeid>", views.cancelar_serviços, name="remover_serviços_view"),
        path("omitir_serviços/<omitirid>", views.omitir_serviços, name="omitir_serviços_view"),
        path("alterar_serviços/<alterarid>", views.alterar_serviços, name="alterar_serviços_view"),
        #=================================================================================
        path("consultar_equipamentos", views.consultar_equipamentos, name="consultar_equipamentos"),
        path("adicionar_equipamentos", views.adicionar_equipamentos, name="adicionar_equipamentos_view"),
        path("cancelar_equipamentos/<removeid>", views.cancelar_equipamentos, name="remover_equipamentos_view"),
        path("omitir_equipamentos/<omitirid>", views.omitir_equipamentos, name="omitir_equipamentos_view"),
        path("alterar_equipamentos/<alterarid>", views.alterar_equipamentos, name="alterar_equipamentos_view"),
]


templates/app.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>

  <title>
    Eventos {% block title %} {% endblock title %}

  </title>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>

  <link rel="stylesheet" href="{% static 'css/bulma.css' %}">
  <link rel="stylesheet" href="{% static 'css/mystyle.css' %}">
  <link rel="stylesheet" href="{% static 'css/materialdesignicons.min.css' %}">
  <link rel="stylesheet" href="{% static 'css/responsive-tables.css' %}">
  <link rel="stylesheet" href="{% static 'css/animated-arrows.css' %}">
  <link rel="icon" href="{% static 'img/logo.png' %}" />
  {% block load %}
  {% endblock load %}

  <style>
    body,
    html {
      min-height: 100%;
      background-size: cover;
      background: linear-gradient(to bottom, #ffffff, #eeeeff) no-repeat fixed center center;
    }

    * {
      outline: none;
    }

    #app {
      position: relative;
      min-height: 100vh;
      padding-bottom: 5rem
    }

    #top-hero-body {
      height: 45vh;
    }

    #page-content {
      margin: -37vh 5vw 0
    }

    #page-content .card {
      min-height: 70vh
    }

    .footer {
      position: absolute;
      bottom: 0;
      width: 100%;
      background-color: #fafafa;
      padding: 1rem 3rem;
    }

    .step-item.is-completed {
      cursor: pointer;
    }

    .step-item.is-active {
      cursor: pointer;
    }

    h1 {
      font-size: 24px !important;
      display: inline-block !important;
    }

    .container {
            position: relative;
            margin-left: auto;
            margin-right: auto;
            width: 80%;
        }

    .center {
            text-align: center;
            margin: auto;
            width: 30%;
            padding: 10px;
        }

    button {
            margin-left :5px 
        }

  </style>
</head>

<body>
  <div id="app">
    {% include 'popup.html'  %}
    {% include 'navbar.html' %}
    <div class="hero is-primary is-bold" id="top-hero">
      <div id="top-hero-body" class="hero-body"></div>
    </div>
    <div class="container">
      <div id="page-content">
        <div class="card">
            <div class="card-content">
            {% block content %}
            <!-- include the content here-->
            {% endblock content %}
          </div>
        </div>
      </div>
    </div>

    <footer class="footer">
      <div style="margin: auto; width: max-content">
        &#169; 2021 Eventos(Grupo 4)
      </div>
    </footer>
  </div>

  <script type="text/javascript" src="{% static 'js/fontawesome.js' %}"></script>
  <script type="text/javascript" src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
  <script type="text/javascript" src="{% static 'js/animated-arrows.js' %}"></script>
  <script type="text/javascript" src="{% static 'js/js_custom.js' %}"></script>
  {% block scripts %}
  {% endblock scripts %}
</body>

</html>

templates/bulma_table.html
{% load django_tables2 %}
{% load i18n %}
{% block table-wrapper %}
{% block table %}
<div class="table-wrapper">
    <table
        class="main-table table has-mobile-cards is-fullwidth is-striped {% block table_class %}{% endblock table_class %}"
        {% if table.fixed %}style="table-layout: fixed;" {% endif %} {% render_attrs table.attrs %}>
        {% block table.thead %}
        {% if table.show_header %}
        <thead {{ table.attrs.thead.as_html }}>
            <tr>
                {% block seta_th %}
                {% endblock seta_th %}
                {% for column in table.columns %}
                <th {% if column.orderable %}class="orderable
                    {% if request.GET.sort == column.order_by_alias %}is-sorting{% endif %}" {% endif %}
                    {% if column.orderable %}
                    onclick="window.location.href = '{% querystring table.prefixed_order_by_field=column.order_by_alias.next %}';"
                    {% endif %} {{ column.attrs.th.as_html }}>
                    {% if column.attrs.abbr %}<abbr title="{{column.attrs.abbr.title}}">{% endif %}
                        {{ column.header }}
                        {% if column.attrs.abbr %}</abbr>{% endif %}
                    {% if column.orderable and request.GET.sort == column.order_by_alias %}
                    {% if column.order_by_alias|slice:"0:1" == "-" %}
                    <span class="icon is-small"><i class="mdi mdi-menu-up"></i></span>
                    {% else %}
                    <span class="icon is-small"><i class="mdi mdi-menu-down"></i></span>
                    {% endif %}
                    {% endif %}
                </th>
                {% endfor %}
            </tr>
        </thead>
        {% endif %}
        {% endblock table.thead %}
        {% block table.tbody %}
        <tbody {{ table.attrs.tbody.as_html }}>
            {% for row in table.paginated_rows %}
            {% block table.tbody.row %}
            <tr {{ row.attrs.as_html }}  style="word-wrap: break-word;">
                {% block seta_tr %}
                {% endblock seta_tr %}
                {% for column, cell in row.items %}
                <td {{ column.attrs.td.as_html }} data-label="{{column.header}}">
                    {% if column.localize == None %}{{ cell }}{% else %}{% if column.localize %}{{ cell|localize }}{% else %}{{ cell|unlocalize }}{% endif %}{% endif %}
                </td>
                {% endfor %}
            </tr>
            {% endblock table.tbody.row %}
            {% block detail %}
            {% endblock detail %}
            {% empty %}
            {% if table.empty_text %}
            {% block table.tbody.empty_text %}
            <tr>
                <td colspan="{{ table.columns|length }}">{{ table.empty_text }}</td>
            </tr>
            {% endblock table.tbody.empty_text %}
            {% endif %}
            {% endfor %}
        </tbody>
        {% endblock table.tbody %}
        {% block table.tfoot %}
        {% if table.has_footer %}
        <tfoot {{ table.attrs.tfoot.as_html }}>
            <tr>
                {% for column in table.columns %}
                <td {{ column.attrs.tf.as_html }}>{{ column.footer }}</td>
                {% endfor %}
            </tr>
        </tfoot>
        {% endif %}
        {% endblock table.tfoot %}
    </table>
</div>
{% endblock table %}

{% block pagination %}

<div class="level">
    <div class="level-left"></div>
    <div class="level-right">
        <div class="level-item">
            <nav class="pagination" role="navigation" aria-label="pagination">
                {% block pagination.range %}
                {% for p in table.page|table_page_range:table.paginator %}
                <ul class="pagination-list">
                    <li>
                        {% if p == table.page.number %}
                        <a class="pagination-link is-current" href="">{{ p }}</a>
                        {% elif p == '...' %}
                        <span class="pagination-ellipsis">&hellip;</span>
                        {% else %}
                        <a class="pagination-link" href="{% querystring table.prefixed_page_field=p %}">
                            {{ p }}
                        </a>
                        {% endif %}
                    </li>
                </ul>
                {% endfor %}
                {% endblock pagination.range %}
                {% block pagination.previous %}
                <a role="button" {% if table.page.has_previous %}
                    href="{% querystring table.prefixed_page_field=table.page.previous_page_number %}" {% else %}
                    disabled="disabled" {% endif %} class="pagination-previous"><span class="icon" aria-hidden="true"><i
                            class="mdi mdi-chevron-left mdi-24px"></i></span></a>
                {% endblock pagination.previous %}
                {% block pagination.next %}
                <a role="button" {% if table.page.has_next %}
                    href="{% querystring table.prefixed_page_field=table.page.next_page_number %}" {% else %}
                    disabled="disabled" {% endif %} class="pagination-next"><span class="icon" aria-hidden="true"><i
                            class="mdi mdi-chevron-right mdi-24px"></i></span></a>
                {% endblock pagination.next %}
            </nav>
        </div>
    </div>
</div>
{% endblock pagination %}
{% block scripts %}
{% endblock scripts %}
{% endblock table-wrapper %}

<head>
    <style>
        th.orderable {
            cursor: pointer;
        }

        th.orderable:hover {
            border-color: #7a7a7a;
        }

        th.orderable.is-sorting {
            border-color: #7a7a7a;
        }

        .table-wrapper .table {
            margin-bottom: 0
        }

        .table-wrapper:not(:last-child) {
            margin-bottom: 1.5rem
        }

        @media screen and (max-width:1023px) {
            .table-wrapper {
                overflow-x: auto
            }
        }

        @media screen and (max-width:768px) {
            .table.has-mobile-cards thead {
                display: none
            }

            .table.has-mobile-cards tfoot th {
                border: 0;
                display: inherit
            }

            .table.has-mobile-cards tr {
                -webkit-box-shadow: 0 2px 3px rgba(10, 10, 10, .1), 0 0 0 1px rgba(10, 10, 10, .1);
                box-shadow: 0 2px 3px rgba(10, 10, 10, .1), 0 0 0 1px rgba(10, 10, 10, .1);
                max-width: 100%;
                position: relative;
                display: block
            }

            .table.has-mobile-cards tr td {
                border: 0;
                display: inherit
            }

            .table.has-mobile-cards tr td:last-child {
                border-bottom: 0
            }

            .table.has-mobile-cards tr:not(:last-child) {
                margin-bottom: 1rem
            }

            .table.has-mobile-cards tr:not([class*=is-]) {
                background: inherit
            }

            .table.has-mobile-cards tr:not([class*=is-]):hover {
                background-color: inherit
            }

            .table.has-mobile-cards tr.detail {
                margin-top: -1rem
            }

            .table.has-mobile-cards tr:not(.detail):not(.is-empty):not(.table-footer) td {
                display: -webkit-box;
                display: -ms-flexbox;
                display: flex;
                width: auto;
                -webkit-box-pack: justify;
                -ms-flex-pack: justify;
                justify-content: space-between;
                text-align: right;
                border-bottom: 1px solid #f5f5f5
            }

            .table.has-mobile-cards tr:not(.detail):not(.is-empty):not(.table-footer) td:before {
                content: attr(data-label);
                font-weight: 600;
                padding-right: .5em;
                text-align: left
            }
        }
    </style>
    {% block style %}
    {% endblock style %}
</head>

templates/bulma_table_details.html
{% extends 'bulma_table.html' %}

{% block table_class %}is-hoverable{% endblock table_class %}

{% block seta_th %}
<th width="40px"></th>
{% endblock seta_th %}

{% block seta_tr %}
<td class="chevron-cell"><a role="button"><span class="icon"><i class="mdi mdi-chevron-right mdi-24px"></i></span></a>
</td>
{% endblock seta_tr %}

{% block detail %}
<tr class="detail">
    <td colspan="{{ table.columns|length|add:'1' }}" style="border-collapse: separate;">
        <div class="detail-container">
            <div style="font-size: 15px;">
                {% block details_content %}
                {% endblock details_content %}
            </div>
        </div>
    </td>
</tr>
{% endblock detail %}

{% block scripts %}
<script>
    $('.main-table > tbody > tr:not(.detail)').click(function (e) {
        $('.main-table > tbody > tr.detail').not($(this).next()).removeClass('is-active');
        $('.main-table > tbody > tr:not(.detail)').not($(this)).find('td.chevron-cell .icon').removeClass('is-expanded');
        $(this).next().toggleClass('is-active');
        $(this).find('td.chevron-cell .icon').toggleClass('is-expanded');
    })
</script>
{% endblock scripts %}

{% block style %}
<style>
    .main-table > tbody > tr:not(.detail) {
        cursor: pointer;
    }

    .main-table > tbody > tr.detail {
        box-shadow: inset 0 1px 3px #dbdbdb;
        background: #fafafa;
        background-color: rgb(250, 250, 250);
    }

    .main-table > tbody > tr.detail .detail-container {
        padding: 1rem;
    }

    .main-table > tbody > tr.detail:hover {
        background-color: #fafafa !important;
    }

    .main-table > tbody > tr.detail:not(.is-active) {
        display: none;
    }

    .main-table > tbody > tr.detail .is-active {
        display: block;
    }

    .icon.is-expanded {
        transform: rotate(90deg);
    }

    .icon {
        transition: transform 150ms ease-out, opacity 86ms ease-out;
    }
</style>
{% endblock style %}

templates/inicio.html

{% extends 'app.html' %}

{% block title %}- Página Inicial{% endblock title %}

{% block content %}
{% load static %}
<div>
  <div class="section">
    <div class="columns">
      <div class="column is-7">
        <h1 class="title has-text-centered">Nova plataforma</h1>
        <h1 class="subtitle is-5 has-text-centered">
          Simples, Intuitivo, Limpo.
        </h1>
        <p>
          A plataforma online de Gestão de Eventos foi renovada pelos alunos em
          âmbito do curso de Licenciatura de Engenharia Informática.
        </p>
      </div>
      <div class="column is-4">
        <img alt="Logo" src="{% static '/img/logo-large.png' %}" />
      </div>
    </div>
  </div>
  <div class="hero is-light">
    <div class="hero-body">
      <div class="columns">
        <div class="column is-8">
          <p>Eventos 2021</p>
          <small>
            Contacto de suporte:
            <a href="">info@ualg.pt</a>
          </small>
        </div>
        <div class="column">
          <img src="{% static '/img/ualg-logo.png' %}" alt="Eventos" />
        </div>
        <div class="column is-1">
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock content%}


templates/mensagem.html
{% extends 'app.html' %}



{% block title %}- {{m}}{% endblock title %}



{% block content %}

<div style="margin-top:5%">

    {% if tipo == 'success'%}
        <article class="message is-success">
            <div class="message-body">
            <p style="text-align: center;">
            <strong>{{m}}</strong>
            </p>
            </div>
        </article>
    {% elif tipo == 'info'%}
        <article class="message is-info">
            <div class="message-body">
            <p style="text-align: center;">
            <strong>{{m}}</strong>
            </p>
            </div>
        </article>
    {% elif tipo == 'warning'%}
        <article class="message is-warning">
            <div class="message-body">
            <p style="text-align: center;">
            <strong>{{m}}</strong>
            </p>
            </div>
        </article> 
    {% elif tipo == 'error'%}
        <article class="message is-danger">
            <div class="message-body">
            <p style="text-align: center;">
            <strong>{{m}}</strong>
            </p>
            </div>
        </article>  
    {% endif %}
</div>
    {% if continuar != 'off' %}
    <div style="text-align: center;position:center;margin-top:4%">
        <a href="{% url 'home' %}">
            <button  class="button">Continuar</button>
        </a>
    </div>
    {% endif %}
    {% endblock content %}

</div>

templates/navbar.html
{% load static %}

<nav id="main-navbar" class="navbar" role="navigation" aria-label="main navigation">
  <div class="navbar-brand">
    <a class="navbar-item logo" href="{% url 'home' %}">
      <img src="{% static 'img/logo-navbar.png' %}" alt="Dia Aberto">
    </a>
  </div>

  <div class="navbar-menu">
    <div class="navbar-start">
      {% if user.TipoUtilizador == 'Administrador'%}
        <div class="navbar-item has-dropdown is-hoverable">
          <a class="navbar-link">
            Eventos
          </a>
          <div class="navbar-dropdown">
            <a href="{% url 'Evento:consultar_eventos_all' %}" class="navbar-item">Consultar Eventos</a>
            <a href="{% url 'Evento:criar_evento' %}" class="navbar-item">Criar Evento</a>
          </div>
        </div>
        <a href="{% url 'Utilizadores:consultar_utilizadores' %}" class="navbar-item">
          Utilizadores
        </a>
        <div class="navbar-item has-dropdown is-hoverable">
          <a class="navbar-link">
            Recurso
          </a>
          <div class="navbar-dropdown">
            <a href="{% url 'Recurso:consultar_serviços' %}" class="navbar-item">Serviços</a>
            <a href="{% url 'Recurso:consultar_salas' %}" class="navbar-item">Salas</a>
            <a href="{% url 'Recurso:consultar_equipamentos' %}" class="navbar-item">Equipamentos</a>
          </div>
        </div>
        <div class="navbar-item has-dropdown is-hoverable">
          <a class="navbar-link">
            Formulário
          </a>
          <div class="navbar-dropdown">
            <a href="{% url 'Formulario:consultar_formularios_special' %}" class="navbar-item">Formulários</a>
            <a href="{% url 'Formulario:consultar_perguntas' 0 None %}" class="navbar-item">Perguntas</a>
          </div>
        </div>
      {% elif user.TipoUtilizador == 'Participante'%}
        <a href="{% url 'Evento:consultar_eventos_validados_all' %}" class="navbar-item">
          Eventos
        </a>
        <a href="{% url 'Inscriçao:consultar_inscricoes_user' user.id %}" class="navbar-item">
          Inscrições
        </a>
      {% elif user.TipoUtilizador == 'Proponente'%}
        <div class="navbar-item has-dropdown is-hoverable">
          <a class="navbar-link">
            Eventos
          </a>
          <div class="navbar-dropdown">
            <a href="{% url 'Evento:consultar_eventos_validados_all' %}" class="navbar-item">Consultar Eventos</a>
            <a href="{% url 'Evento:consultar_eventos_proponente_all' %}" class="navbar-item">Consultar os meus Eventos</a>
            <a href="{% url 'Evento:criar_evento' %}" class="navbar-item">Criar Evento</a>
          </div>
        </div>
      {% else %}
        <a href="{% url 'Evento:consultar_eventos_validados_all' %}" class="navbar-item">
          Eventos
        </a>
      {% endif %}
    </div>
    <div class="navbar-end">
      <div class="navbar-item">
        {% if user.is_authenticated %}
          <a href="{% url 'Utilizadores:perfil' %}" class="navbar-item">
            Perfil {{user.username}}
          </a>
          <a href="{% url 'Utilizadores:logout' %}" class="navbar-item">
            Logout
          </a>
        {% else %}
          <a href="{% url 'Utilizadores:register' %}" class="navbar-item">
            Registar-se
          </a>
          <a href="{% url 'Utilizadores:login' %}" class="navbar-item">
            Login
          </a>
        {% endif %}
      </div>
    </div>
  </div>
</nav>



templates/popup.html
<div id="msg" class="dialog modal">
    <div class="modal-background"></div>
    <div class="modal-card animation-content">
        <section class="modal-card-body is-titleless" style="border-top-left-radius: 6px; border-top-right-radius: 6px;">
            <div class="media">
                <div class="media-content">
                    <p id='text-00'></p>
                </div>
            </div>
        </section>
        <footer class="modal-card-foot">
            <button onclick="alert.cancelar()" class="button" id='dialog-cancel'>Cancelar</button>
            <button onclick="alert.confirmar()" class="button is-success" id='dialog-confirm'>Confirmar</button>
        </footer>
    </div>
</div>