Evento/urls.py
from django.urls import path
from .import views


app_name = "Evento"

urlpatterns = [
	path("consultar_eventos/<cat_id>", views.consultar_eventos, name="consultar_eventos"),
	path("consultar_eventos_all", views.consultar_eventos_all, name="consultar_eventos_all"),
    path("consultar_eventos_proponente_all", views.consultar_eventos_proponente_all, name="consultar_eventos_proponente_all"),
    path("consultar_eventos_validados_all", views.consultar_eventos_validados_all, name="consultar_eventos_validados_all"),
    path("consultar_eventos_proponente/<cat_id>", views.consultar_eventos_proponente, name="consultar_eventos_proponente"),
    path("consultar_eventos_validados/<cat_id>", views.consultar_eventos_validados, name="consultar_eventos_validados"),

	path("visualizar_evento/<evento_id>", views.visualizar_evento, name="visualizar_evento"),

    path("criar_evento", views.criar_evento, name="criar_evento"),

	path("cancelar_evento/<evento_id>", views.cancelar_evento, name="cancelar_evento"),

	path("editar_evento/<evento_id>", views.editar_evento, name="editar_evento"),

    path("submeter_evento/<evento_id>", views.submeter_evento, name="submeter_evento"),
    path("validar_evento/<evento_id>", views.validar_evento, name="validar_evento"),

    path("criar_logistica/<evento_id>", views.criar_logistica, name="criar_logistica"),

    path("visualizar_logistica/<evento_id>", views.visualizar_logistica, name="visualizar_logistica"),

    path("editar_logistica/<logistica_id>", views.editar_logistica, name="editar_logistica"),

    path("cancelar_logistica/<logistica_id>", views.cancelar_logistica, name="cancelar_logistica"),

    path("submeter_logistica/<logistica_id>", views.submeter_logistica, name="submeter_logistica"),
    path("validar_logistica/<logistica_id>", views.validar_logistica, name="validar_logistica"),
    
    path("atribuir_sala/<evento_id>", views.atribuir_sala, name="atribuir_sala"),
    path("atribuir_equipamento/<evento_id>", views.atribuir_equipamento, name="atribuir_equipamento"),
    path("atribuir_serviço/<evento_id>", views.atribuir_serviço, name="atribuir_serviço"),
    
    path("cancelar_atribuir_sala/<removeid>", views.cancelar_atribuiçao_sala, name="cancelar_atribuir_sala"),
    path("cancelar_atribuir_equipamento/<removeid>", views.cancelar_atribuiçao_equipamento, name="cancelar_atribuir_equipamento"),
    path("cancelar_atribuir_serviço/<removeid>", views.cancelar_atribuiçao_serviço, name="cancelar_atribuir_serviço"),
]

Formulario/urls.py
from django.urls import path
from . import views
app_name = "Formulario"

urlpatterns = [
    path("consultar_perguntas/<id>/<formulario_id>", views.consultar_perguntas, name="consultar_perguntas"),
    path("add_pergunta/<formulario_id>", views.add_pergunta, name="add_pergunta"),
    path("add_opcao_resposta/<pergunta_id>/<formulario_id>", views.add_opcao_resposta, name="add_opcao_resposta"),
    path("remover_perguntas/<pergunta_id>/<formulario_id>", views.remover_pergunta, name="remover_pergunta"),
    path("delete_resposta/<pergunta_id>/<resposta_id>/<formulario_id>", views.delete_resposta, name="delete_resposta"),
    path("editar_pergunta/<pergunta_id>/<formulario_id>", views.editar_pergunta, name="editar_pergunta"),
    path("editar_opcao_resposta/<pergunta_id>/<resposta_id>/<formulario_id>", views.editar_opcao_resposta, name="editar_opcao_resposta"),
    
    path("consultar_formularios/<evento_id>", views.consultar_formularios, name="consultar_formularios"),
    path("consultar_formularios_special", views.consultar_formularios_special, name="consultar_formularios_special"),
    
    path("add_formulario/<evento_id>", views.add_formulario, name="add_formulario"),
    path("add_formulario_special", views.add_formulario_special, name="add_formulario_special"),

    path("add_pergunta_ao_formulario/<formulario_id>", views.add_pergunta_ao_formulario, name="add_pergunta_ao_formulario"),
    path("editar_formulario/<formulario_id>", views.editar_formulario, name="editar_formulario"),
    path("editar_formulario_special/<formulario_id>", views.editar_formulario_special, name="editar_formulario_special"),
    path("eliminar_formulario/<formulario_id>", views.eliminar_formulario, name="eliminar_formulario"),
    path("alterar_estado_formulario/<formulario_id>", views.alterar_estado_formulario, name="alterar_estado_formulario"),
    path("add_pergunta_ao_formulario_action/<pergunta_id>/<formulario_id>", views.add_pergunta_ao_formulario_action, name="add_pergunta_ao_formulario_action"),
    path("pergunta_move_up/<pergunta_id>/<formulario_id>", views.pergunta_move_up, name="pergunta_move_up"),
    path("pergunta_move_down/<pergunta_id>/<formulario_id>", views.pergunta_move_down, name="pergunta_move_down"),

    path("remover_pergunta_do_formulario/<pergunta_id>/<formulario_id>", views.remover_pergunta_do_formulario, name="remover_pergunta_do_formulario"),
    path("editar_pergunta_do_formulario/<pergunta_id>/<formulario_id>", views.editar_pergunta_do_formulario, name="editar_pergunta_do_formulario"),
    
]

Inscriçao/urls.py
from django.urls import path
from . import views

app_name = "Inscriçao"

urlpatterns = [
    # DEFAULT PATH
    path("", views.consultar_inscricoes_all, name="consultar_inscricoes"),
       
    # Consultar inscrições
    path(
        "consultar_user/<user_id>",
        views.consultar_inscricoes_user,
        name="consultar_inscricoes_user",
    ),
    path(
        "consultar_evento/<evento_id>",
        views.consultar_inscricoes_evento,
        name="consultar_inscricoes_evento",
    ),
    path(
        "consultar_all",
        views.consultar_inscricoes_all,
        name="consultar_inscricoes_all",
    ),

    # Consultar inscrição
    path(
        "consultar/<inscricao_id>",
        views.consultar,
        name="consultar",
    ),
    # Editar inscrição
    path(
        "editar/<inscricao_id>",
        views.editar,
        name="editar",
    ),
    # Criar Inscrição
    path(
        "criar/<evento_id>",
        views.criar,
        name="criar",
    ),
    # Remover Inscrição
    path(
        "remover/<inscricao_id>",
        views.remover,
        name="remover",
    ),
    # Validar Inscrição
    path(
        "validar/<inscricao_id>",
        views.validar,
        name="validar",
    ),
    # Checkin Inscrição
    path(
        "checkin/<evento_id>",
        views.checkin,
        name="checkin",
    ),

]

LES/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = "LES"

urlpatterns = [
    #Ricardo
    path('Formulario/', include('Formulario.urls')),

    #Filipe
    path('Evento/', include('Evento.urls')),
    #Guilherme
    path('Inscricao/', include('Inscriçao.urls')),
    #Dario
    path('Recurso/', include('Recurso.urls')),

    path('admin/', admin.site.urls),

    path('Utilizadores/', include('Utilizadores.urls')),

    path('', views.home, name='home'),
]

Evento/views.py
from django.shortcuts import render
from .models import Evento, TipoDeEvento, PedidoDeRecurso
from Utilizadores.models import *
from django.shortcuts import get_object_or_404
from django.shortcuts import redirect
from django.http import HttpResponseRedirect
from django.contrib import messages
from .forms import *
from Recurso.models import *

# Create your views here.

def consultar_eventos(request, cat_id):
    categories = TipoDeEvento.objects.all()
    category = get_object_or_404(TipoDeEvento, id = cat_id)
    Eventos = Evento.objects.filter(tipo_de_eventoid = category).filter().order_by('data')
    Logisticas = PedidoDeRecurso.objects.all()
    return render(request, 'consultar_eventos.html', {'Eventos' : Eventos,
                                                      'Logisticas' : Logisticas,
                                                      'TipoDeEvento' : categories})

def consultar_eventos_all(request):
    categories = TipoDeEvento.objects.all()
    Eventos = Evento.objects.filter().order_by('data')
    return render(request, 'consultar_eventos.html', {'Eventos' : Eventos,
                                                      'TipoDeEvento' : categories})

def consultar_eventos_proponente_all(request):
    categories = TipoDeEvento.objects.all()
    proponente = Proponente.objects.get(utilizadorid = request.user)
    Eventos = Evento.objects.filter(proponenteutilizadorid = proponente).order_by('data')
    return render(request, 'consultar_eventos.html', {'Eventos' : Eventos,
                                                      'TipoDeEvento' : categories})

def consultar_eventos_validados_all(request):
    categories = TipoDeEvento.objects.all()
    Eventos = Evento.objects.filter(estado = 'Validado').order_by('data')
    estado = 'normal'
    return render(request, 'consultar_eventos.html', {'Eventos' : Eventos,
                                                      'TipoDeEvento' : categories,
                                                      'estado' : estado})


def consultar_eventos_proponente(request, cat_id):
    categories = TipoDeEvento.objects.all()
    category = get_object_or_404(TipoDeEvento, id = cat_id)
    proponente = Proponente.objects.get(utilizadorid = request.user)
    Eventos = Evento.objects.filter(proponenteutilizadorid = proponente, tipo_de_eventoid = category).order_by('data')
    return render(request, 'consultar_eventos.html', {'Eventos' : Eventos,
                                                      'TipoDeEvento' : categories})

def consultar_eventos_validados(request, cat_id):
    categories = TipoDeEvento.objects.all()
    category = get_object_or_404(TipoDeEvento, id = cat_id)
    Eventos = Evento.objects.filter(estado = 'Validado' , tipo_de_eventoid = category).order_by('data')
    estado = 'normal'
    return render(request, 'consultar_eventos.html', {'Eventos' : Eventos,
                                                      'TipoDeEvento' : categories,
                                                      'estado' : estado})

def visualizar_evento(request, evento_id):
    Evento_view = Evento.objects.get(pk = evento_id)
    Evento_Equipamentos_view = EventoEquipamentos.objects.filter(eventoId = evento_id)
    Evento_Local_view = EventoLocais.objects.filter(eventoId = evento_id)
    Evento_Servicos_view = EventoServicos.objects.filter(eventoId = evento_id)
    return render(request, 'visualizar_evento.html', {'Evento' : Evento_view, 'Equipamento' : Evento_Equipamentos_view,
                                                      'Servico' : Evento_Servicos_view, 'Local' : Evento_Local_view})


def criar_evento(request):
    submitted = False
    if request.method == "POST":
        form = evento_form(request.POST)
        if form.is_valid():
            new_form = Evento(
                    tipo_de_eventoid=get_object_or_404(
                        TipoDeEvento, id=form.data["tipo_de_eventoid"]
                    ),
                    proponenteutilizadorid=get_object_or_404(
                        Proponente, utilizadorid=request.user
                    ),
                    nome=form.data["nome"],
                    descrição=form.data["descrição"],
                    data=form.data["data"],
                    hora=form.data["hora"],
                    duração=form.data["duração"],
                    valor=form.data["valor"],
                    )
            new_form.save()
            return HttpResponseRedirect('/Evento/criar_evento?submitted=True')
    else:
        form = evento_form
        if 'submitted' in request.GET:
            submitted = True
    return render(request, 'criar_evento.html', {'form' : form, 'submitted' : submitted})


def cancelar_evento(request, evento_id):
    Evento_view = Evento.objects.get(pk = evento_id)
    Evento_view.delete()

    if request.user.TipoUtilizador == 'Proponente': 
        return redirect('Evento:consultar_eventos_proponente_all')
    elif request.user.TipoUtilizador == 'Administrador':
        return redirect('Evento:consultar_eventos_all')



def editar_evento(request, evento_id):
    Evento_view = Evento.objects.get(pk = evento_id)
    form = evento_form(request.POST or None, instance = Evento_view)
    if form.is_valid():
        form.save()
        return redirect('Evento:consultar_eventos_proponente_all')
    return render(request, 'editar_evento.html', {'Evento' : Evento_view, 
                                                  'form' : form})
                                                  

def submeter_evento(request, evento_id):
    Evento_view = Evento.objects.get(pk = evento_id)
    Evento_view.estado='Submetido'
    Evento_view.save()
    return redirect('Evento:consultar_eventos_proponente_all')

def validar_evento(request, evento_id):
    Evento_view = Evento.objects.get(pk = evento_id)
    Evento_view.estado='Validado'
    Evento_view.save()
    return redirect('Evento:consultar_eventos_all')


def criar_logistica(request, evento_id):
    submitted = False
    if request.method == "POST":
        form = logistica_form(request.POST)
        if form.is_valid():
            capacidade=form.data["capacidade"]
            if capacidade == '':
                capacidade = None
            new_form = PedidoDeRecurso(
                    eventoid = get_object_or_404(Evento, id = evento_id),
                    tipo_de_recursoid=get_object_or_404(
                        TipoDeRecurso, id=form.data["tipo_de_recursoid"]
                    ),
                    quantidade=form.data["quantidade"],
                    dia_inicial=form.data["dia_inicial"],
                    hora_inicial=form.data["hora_inicial"],
                    dia_final=form.data["dia_final"],
                    hora_final=form.data["hora_final"],
                    capacidade=capacidade
                    )
            new_form.save()
            return HttpResponseRedirect('/Evento/criar_logistica/{evento_id}?submitted=True')
    else:
        form = logistica_form
        if 'submitted' in request.GET:
            submitted = True
    return render(request, 'criar_logistica.html', {'form' : form, 'submitted' : submitted})


def visualizar_logistica(request, evento_id):
    Logistica_view = PedidoDeRecurso.objects.filter(eventoid = evento_id)
    Evento_view = Evento.objects.get(pk = evento_id)
    return render(request, 'visualizar_logistica.html', {'Logistica' : Logistica_view, 'Evento' : Evento_view})


def editar_logistica(request, logistica_id):
    Logistica_view = PedidoDeRecurso.objects.get(pk = logistica_id)

    Logistica = PedidoDeRecurso.objects.filter(eventoid = Logistica_view.eventoid)
    Evento_view = Evento.objects.get(pk = Logistica_view.eventoid.id)

    form = logistica_form(request.POST or None, instance = Logistica_view)
    if form.is_valid():
        form.save()
        return render(request, 'visualizar_logistica.html', {'Logistica' : Logistica, 'Evento' : Evento_view})

    return render(request, 'editar_logistica.html', {'Logistica' : Logistica_view, 
                                                  'form' : form})

def cancelar_logistica(request, logistica_id):
    Logistica_view = PedidoDeRecurso.objects.get(pk = logistica_id)

    Logistica = PedidoDeRecurso.objects.filter(eventoid = Logistica_view.eventoid)
    Evento_view = Evento.objects.get(pk = Logistica_view.eventoid.id)

    Logistica_view.delete()
    return render(request, 'visualizar_logistica.html', {'Logistica' : Logistica, 'Evento' : Evento_view})

def submeter_logistica(request, logistica_id):
    Logistica_view = PedidoDeRecurso.objects.get(pk = logistica_id)

    Logistica = PedidoDeRecurso.objects.filter(eventoid = Logistica_view.eventoid)
    Evento_view = Evento.objects.get(pk = Logistica_view.eventoid.id)

    Logistica_view.estado='Submetido'
    Logistica_view.save()
    return render(request, 'visualizar_logistica.html', {'Logistica' : Logistica, 'Evento' : Evento_view})

def validar_logistica(request, logistica_id):
    Logistica_view = PedidoDeRecurso.objects.get(pk = logistica_id)

    Logistica = PedidoDeRecurso.objects.filter(eventoid = Logistica_view.eventoid)
    Evento_view = Evento.objects.get(pk = Logistica_view.eventoid.id)

    Logistica_view.estado='Validado'
    Logistica_view.save()
    return render(request, 'visualizar_logistica.html', {'Logistica' : Logistica, 'Evento' : Evento_view})

#===================================Atribuições=======================================

def atribuir_sala(request, evento_id):
    Evento_view = Evento.objects.get(pk = evento_id)
    if request.method == "POST":
        form = atribuir_sala_form(request.POST)
        if form.is_valid():

Evento/templates/consultar_eventos.html
{% extends 'app.html' %}

{% block title %}- Consultar Equipamentos {% endblock title %}

{% block content %}
{% load static %}
<div class="center">
  <h1>Consultar Eventos</h1>
</div>
<br><br>
<div class="dropdown">
  <a class="dropdown-toggle" data-toggle="dropdown"><button type="button" class="btn btn-primary">Categorias</button></a>
  <div class="dropdown-menu">
    {% if user.TipoUtilizador == 'Administrador' %}
      <a class="dropdown-item" href="{% url 'Evento:consultar_eventos_all' %}">All</a>
    {% elif estado != 'normal' %}
      <a class="dropdown-item" href="{% url 'Evento:consultar_eventos_proponente_all' %}">All</a>
    {% else %}
      <a class="dropdown-item" href="{% url 'Evento:consultar_eventos_validados_all' %}">All</a>
    {% endif %}
    {% for c in TipoDeEvento %}
      {% if user.TipoUtilizador == 'Administrador' %}
        <a class="dropdown-item" href="{% url 'Evento:consultar_eventos' c.id %}">{{c.nome}}</a>
      {% elif estado != 'normal' %}
        <a class="dropdown-item" href="{% url 'Evento:consultar_eventos_proponente' c.id %}">{{c.nome}}</a>
      {% else %}
        <a class="dropdown-item" href="{% url 'Evento:consultar_eventos_validados' c.id %}">{{c.nome}}</a>
      {% endif %}
    {% endfor %}
  </div>
</div>
{% if user.is_authenticated%}
  {% if user.TipoUtilizador != 'Participante' %}
    <a href="{% url 'Evento:criar_evento' %}">
      <button type="button" class="btn btn-primary">Criar evento</button>
    </a>
  {% endif %}
{% endif %}
<br><br>
  <table class="table">
    <tr>
      <th>Nome</th>
      <th>Tipo de evento</th>
      {% if estado != 'normal'%}
        <th>Estado</th>
      {% endif %}
      <th>Descrição</th>
      <th>Data</th>
      <th>Ações</th>
    </tr>
    {% for e in Eventos %}
    <tr>
      <td>{{e.nome}}</td>
      <td>{{e.tipo_de_eventoid.nome}}</td>
      {% if estado != 'normal' %}
        <td>{{e.estado}}</td>
      {% endif %}
      <td>{{e.descrição}}</td>
      <td>{{e.data}}</td>
      <td>
          <a href="{% url 'Evento:visualizar_evento' e.id %}">
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-eye" viewBox="0 0 16 16">
            <path d="M16 8s-3-5.5-8-5.5S0 8 0 8s3 5.5 8 5.5S16 8 16 8zM1.173 8a13.133 13.133 0 0 1 1.66-2.043C4.12 4.668 5.88 3.5 8 3.5c2.12 0 3.879 1.168 5.168 2.457A13.133 13.133 0 0 1 14.828 8c-.058.087-.122.183-.195.288-.335.48-.83 1.12-1.465 1.755C11.879 11.332 10.119 12.5 8 12.5c-2.12 0-3.879-1.168-5.168-2.457A13.134 13.134 0 0 1 1.172 8z"/>
            <path d="M8 5.5a2.5 2.5 0 1 0 0 5 2.5 2.5 0 0 0 0-5zM4.5 8a3.5 3.5 0 1 1 7 0 3.5 3.5 0 0 1-7 0z"/>
          </svg></a>

          {% if user.is_authenticated%}

            {% if e.estado != "Validado" %}
              <a>|</a>
              <a href="{% url 'Evento:cancelar_evento' e.id %}" onclick="clicked(event)"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash" viewBox="0 0 16 16">
                <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z"/>
                <path fill-rule="evenodd" d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z"/>
              </svg></a>
              <a>|</a>
              <a href="{% url 'Evento:editar_evento' e.id %}"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pencil" viewBox="0 0 16 16">
                <path d="M12.146.146a.5.5 0 0 1 .708 0l3 3a.5.5 0 0 1 0 .708l-10 10a.5.5 0 0 1-.168.11l-5 2a.5.5 0 0 1-.65-.65l2-5a.5.5 0 0 1 .11-.168l10-10zM11.207 2.5 13.5 4.793 14.793 3.5 12.5 1.207 11.207 2.5zm1.586 3L10.5 3.207 4 9.707V10h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.293l6.5-6.5zm-9.761 5.175-.106.106-1.528 3.821 3.821-1.528.106-.106A.5.5 0 0 1 5 12.5V12h-.5a.5.5 0 0 1-.5-.5V11h-.5a.5.5 0 0 1-.468-.325z"/>
              </svg></a>
            {% endif %}
            <a>|</a>
          <div class="dropdown">
            <a class="dropdown-toggle" data-toggle="dropdown"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-three-dots" viewBox="0 0 16 16">
  <path d="M3 9.5a1.5 1.5 0 1 1 0-3 1.5 1.5 0 0 1 0 3zm5 0a1.5 1.5 0 1 1 0-3 1.5 1.5 0 0 1 0 3zm5 0a1.5 1.5 0 1 1 0-3 1.5 1.5 0 0 1 0 3z"/>
</svg></a>
            <div class="dropdown-menu">
            {% if user.TipoUtilizador == 'Proponente' %}
              {% if e.estado == "Não submetido" %}
                <a class="dropdown-item" href="{% url 'Evento:submeter_evento' e.id %}">Submeter Evento</a>
                <a class="dropdown-item" href="{% url 'Evento:criar_logistica' e.id %}">Criar pedido de logistica</a>
              {% endif %}
              
              {% if e.proponenteutilizadorid.utilizadorid == user %}
                <a class="dropdown-item" href="{% url 'Evento:visualizar_logistica' e.id %}">Visualizar Logistica</a>
              {% endif %}

            {% endif %}
            {% if user.TipoUtilizador == 'Administrador' %}
              {% if e.estado == "Submetido" %}
                <a class="dropdown-item" href="{% url 'Evento:validar_evento' e.id %}">Validar Evento</a>
              {% endif %}
              <a class="dropdown-item" href="{% url 'Evento:criar_logistica' e.id %}">Criar Logistica</a>
              <a class="dropdown-item" href="{% url 'Evento:visualizar_logistica' e.id %}">Visualizar Logistica</a>
              <a class="dropdown-item" href="{% url 'Evento:atribuir_sala' e.id %}">Atribuir sala</a>
              <a class="dropdown-item" href="{% url 'Evento:cancelar_atribuir_sala' e.id %}">Cancelar atribuição sala</a>
              <a class="dropdown-item" href="{% url 'Evento:atribuir_equipamento' e.id %}">Atribuir equipamento</a>
              <a class="dropdown-item" href="{% url 'Evento:cancelar_atribuir_equipamento' e.id %}">Cancelar atribuição equipamento</a>
              <a class="dropdown-item" href="{% url 'Evento:atribuir_serviço' e.id %}">Atribuir serviço</a>
              <a class="dropdown-item" href="{% url 'Evento:cancelar_atribuir_serviço' e.id %}">Cancelar atribuição serviço</a>  
              <a class="dropdown-item" href="{% url 'Formulario:consultar_formularios' e.id %}">Consultar formulários</a>
            {% endif %}
          {% endif %} 
      </td>
    </tr>
    {% endfor %}
  </table>
</div>
</div>
  <script>
    function clicked(e)
    {
        if(!confirm('Tem a certeza que pretende cancelar este Evento')) {
            e.preventDefault();
        }
    }
  </script>
  {% endblock content %}

Evento/templates/visualizar_evento.html
{% extends 'app.html' %}

{% block title %}- Visualizar Evento {% endblock title %}

{% block content %}
{% load static %}
<div class="center">
<div class="card" style="width: 200px; text-align: center;">
  <div class="card-body">
    <h5 class="card-title">{{Evento.nome}}</h5><br>
    <p class="card-text">{{Evento.descrição}}</p>
  </div>
  <ul class="list-group list-group-flush">
    <li class="list-group-item">{{Evento.tipo_de_eventoid.nome}}</li>
    <li class="list-group-item">{{Evento.data}}</li>
    <li class="list-group-item">{{Evento.hora}}</li>
    <li class="list-group-item">Duração: {{Evento.duração}}h</li>
    <li class="list-group-item">Valor: {{Evento.valor}}€</li>
    
    <li class="list-group-item">Salas: {% for l in Local %}{{l.localId}},{% endfor %}</li>
    
    <li class="list-group-item">Serviços: {% for s in Servico %}{{s.servicoId}},{% endfor %}</li>
    
    <li class="list-group-item">Equipamentos: {% for e in Equipamento %}{{e.equipamentoId}},{% endfor %}</li>
    
  </ul>
  <div class="card-body">
    {% if user.TipoUtilizador == 'Administrador' %}
      <a href="{% url 'Evento:consultar_eventos_all' %}" class="card-link">Voltar</a>
    {% elif user == Evento.proponenteutilizadorid.utilizadorid %}
      <a href="{% url 'Evento:consultar_eventos_proponente_all' %}" class="card-link">Voltar</a>
    {% elif user.TipoUtilizador == 'Participante' %}
      <a href="{% url 'Inscriçao:criar' Evento.id %}" class="card-link">Inscrever-se</a>
      <a>|</a>   
      <a href="{% url 'Evento:consultar_eventos_validados_all' %}" class="card-link">Voltar</a> 
    {% else %}
      <a href="{% url 'Evento:consultar_eventos_validados_all' %}" class="card-link">Voltar</a>  
    {% endif %}
  </div>
</div>
</div>
{% endblock content %}