LES/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = "LES"

urlpatterns = [
    #Ricardo
    path('Formulario/', include('Formulario.urls')),

    #Filipe
    path('Evento/', include('Evento.urls')),
    #Guilherme
    path('Inscricao/', include('Inscriçao.urls')),
    #Dario
    path('Recurso/', include('Recurso.urls')),

    path('admin/', admin.site.urls),

    path('Utilizadores/', include('Utilizadores.urls')),

    path('', views.home, name='home'),
]

Recurso/urls.py
from django.urls import path
from . import views
app_name = "Recurso"

urlpatterns = [
        path("consultar_salas", views.consultar_salas, name="consultar_salas"),
        path("adicionar_salas", views.adicionar_salas, name="adicionar_salas_view"),
        path("cancelar_salas/<removeid>", views.cancelar_salas, name="remover_salas_view"),
        path("omitir_salas/<omitirid>", views.omitir_salas, name="omitir_salas_view"),
        path("alterar_salas/<alterarid>", views.alterar_salas, name="alterar_salas_view"),
        #=================================================================================
        path("consultar_serviços", views.consultar_serviços, name="consultar_serviços"),
        path("adicionar_serviços", views.adicionar_serviços, name="adicionar_serviços_view"),
        path("cancelar_serviços/<removeid>", views.cancelar_serviços, name="remover_serviços_view"),
        path("omitir_serviços/<omitirid>", views.omitir_serviços, name="omitir_serviços_view"),
        path("alterar_serviços/<alterarid>", views.alterar_serviços, name="alterar_serviços_view"),
        #=================================================================================
        path("consultar_equipamentos", views.consultar_equipamentos, name="consultar_equipamentos"),
        path("adicionar_equipamentos", views.adicionar_equipamentos, name="adicionar_equipamentos_view"),
        path("cancelar_equipamentos/<removeid>", views.cancelar_equipamentos, name="remover_equipamentos_view"),
        path("omitir_equipamentos/<omitirid>", views.omitir_equipamentos, name="omitir_equipamentos_view"),
        path("alterar_equipamentos/<alterarid>", views.alterar_equipamentos, name="alterar_equipamentos_view"),
]


Recurso/models.py
from django.db import models


class Campus(models.Model):
    id = models.AutoField(db_column='ID', primary_key=True)  # Field name made lowercase.
    nome = models.CharField(db_column='Nome', unique=True, max_length=255, blank=True, null=True)  # Field name made lowercase.
    morada = models.CharField(db_column='Morada', max_length=255, blank=True, null=True)  # Field name made lowercase.

    def __str__(self):
        return str(self.nome)

    class Meta:
        managed = True
        db_table = 'Campus'

class Edificio(models.Model):
    id = models.AutoField(db_column='ID', primary_key=True)  # Field name made lowercase.
    campusid = models.ForeignKey(Campus, models.SET_NULL, verbose_name='Campus', default=None, null=True, db_column='CampusID')  # Field name made lowercase.
    nome = models.CharField(db_column='Nome', verbose_name='Edificio', max_length=255, blank=True, null=True)  # Field name made lowercase.

    def __str__(self):
        return str(self.nome)
    
    class Meta:
        managed = True
        db_table = 'Edificio'

class Equipamento(models.Model):
    recursoid = models.OneToOneField('Recurso', models.DO_NOTHING, db_column='RecursoID', primary_key=True)  # Field name made lowercase.

    def __str__(self):
        return str(self.recursoid.nome)

    class Meta:
        managed = True
        db_table = 'Equipamento'

class Recurso(models.Model):
    id = models.AutoField(db_column='ID', primary_key=True) 
    nome = models.CharField(db_column='Nome', max_length=255, blank=True, null=True) 
    estado = models.ForeignKey('Recurso_estado', models.DO_NOTHING, default=None, null=False, db_column='Estado')

    def __str__(self):
        return str(self.nome)

    class Meta:
        managed = True
        db_table = 'Recurso'

class Recurso_estado(models.Model):
    id = models.AutoField(db_column='ID', primary_key=True) 
    Estado = models.CharField(db_column='Estado', max_length=255, blank=True, null=True) 

    def __str__(self):
        return str(self.Estado)

    class Meta:
        managed = True
        db_table = 'Recurso_estado'

class Sala(models.Model):
    recursoid = models.OneToOneField(Recurso, models.DO_NOTHING, verbose_name='Sala', db_column='RecursoID', primary_key=True)  # Field name made lowercase.
    edificioid = models.ForeignKey(Edificio, models.SET_NULL, verbose_name='Edificio', default=None, null=True, db_column='EdificioID')  # Field name made lowercase.
    lugares = models.IntegerField(db_column='Lugares', blank=True, null=True)  # Field name made lowercase.

    def __str__(self):
        return str(self.recursoid)

    class Meta:
        managed = True
        db_table = 'Sala'

class Serviço(models.Model):
    recursoid = models.OneToOneField(Recurso, models.DO_NOTHING, db_column='RecursoID', primary_key=True)  # Field name made lowercase.
    
    def __str__(self):
        return str(self.recursoid.nome)

    class Meta:
        managed = True
        db_table = 'Serviço'

class TipoDeRecurso(models.Model):
    id = models.AutoField(db_column='ID', primary_key=True)  # Field name made lowercase.
    nome = models.CharField(db_column='Nome', unique=True,max_length=255, blank=True, null=True)  # Field name made lowercase.

    def __str__(self):
        return str(self.nome)

    class Meta:
        managed = True
        db_table = 'Tipo de recurso'

Recurso/forms.py
from django import forms
from django.forms import ModelForm
from .models import *

class salas_form(ModelForm):
    class Meta:
        model = Sala
        fields = ('edificioid', 'lugares')

        widgets = {
			'edificioid' : forms.Select(attrs={'class' : 'form-control'}),
			'lugares' : forms.TextInput(attrs={'class' : 'form-control'}),
		}
        
class edificios_form(ModelForm):
    class Meta:
        model = Edificio
        fields = ('id', 'campusid', 'nome',)
        
class campus_form(ModelForm):
    class Meta:
        model = Campus
        fields = ('nome', 'morada')
        
class recursos_form(ModelForm):
    class Meta:
        model = Recurso
        fields = ('nome', 'estado')

        widgets = {
			'nome' : forms.TextInput(attrs={'class' : 'form-control'}),
			'estado' : forms.Select(attrs={'class' : 'form-control'}),
		}

Recurso/views.py
from django.shortcuts import render, redirect
from .models import *
from .forms import *
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404

def consultar_salas(request):
	return render(request, "consultar_salas.html", {'salas' : Sala.objects.all, 'edificios': Edificio.objects.all()})

def adicionar_salas(request):
    submitted = False
    error = "Sala já existe"
    errorState = False
    if request.method == "POST":
        r_form = recursos_form(request.POST)
        s_form = salas_form(request.POST)
        if s_form.is_valid() and r_form.is_valid():
            if Recurso.objects.filter(nome = r_form.data['nome']).exists():
                errorState = True
                return render(request, "adicionar_salas.html", {'s_form':s_form, 'r_form':r_form, 'submitted':submitted, 'error':error, 'errorState':errorState})
            else:
                new_id = r_form.save()
                new_sala = Sala(recursoid = new_id, edificioid = get_object_or_404(Edificio, id = s_form.data['edificioid']), lugares = s_form.data['lugares'])
                new_sala.save()
            return HttpResponseRedirect('/Recurso/consultar_salas?submitted=True')
    else:
        r_form = recursos_form()
        s_form = salas_form()
        if 'submitted' in request.GET:
            submitted = True
    return render(request, "adicionar_salas.html", {'s_form':s_form, 'r_form':r_form, 'submitted':submitted})    

def cancelar_salas(request, removeid):
    Sala.objects.get(pk = removeid).delete()
    return redirect('Recurso:consultar_salas')

def omitir_salas(request, omitirid):
    omit = get_object_or_404(Edificio, id = omitirid)
    salas = Sala.objects.filter(edificioid = omit)
    return render(request, "consultar_salas.html", {'salas': salas,
                                                    'edificios': Edificio.objects.all()})

def alterar_salas(request, alterarid):
    error = "Sala já existe"
    errorState = False
    sala_change = Sala.objects.get(pk = alterarid)
    recurso_change = Recurso.objects.get(pk = alterarid)
    s_form = salas_form(request.POST or None, instance=sala_change)
    r_form = recursos_form(request.POST or None, instance=recurso_change)
    if s_form.is_valid() and r_form.is_valid():
        r_form.save()
        s_form.save()
        return redirect('Recurso:consultar_salas')
    return render(request, "alterar_sala.html", {'sala_change': sala_change, 'recurso_change': recurso_change, 's_form':s_form, 'r_form':r_form})

#======================================================================================================================================================

def consultar_serviços(request):
	return render(request, "consultar_serviços.html", {'serviços' : Serviço.objects.all, 'tipos': Recurso_estado.objects.all()})

def adicionar_serviços(request):
    submitted = False
    error = "Serviço já existe"
    errorState = False
    if request.method == "POST":
        r_form = recursos_form(request.POST)
        if r_form.is_valid():
            if Recurso.objects.filter(nome = r_form.data['nome']).exists():
                errorState = True
                return render(request, "adicionar_serviços.html", {'r_form':r_form, 'submitted':submitted, 'error':error, 'errorState':errorState})
            else:
                new_rid = r_form.save()
                new_serviço = Serviço(recursoid = new_rid)
                new_serviço.save()
            return HttpResponseRedirect('/Recurso/consultar_serviços?submitted=True')
    else:
        r_form = recursos_form()
        if 'submitted' in request.GET:
            submitted = True
    return render(request, "adicionar_serviços.html", {'r_form':r_form, 'submitted':submitted})

def cancelar_serviços(request, removeid):
    Serviço.objects.get(pk = removeid).delete()
    return redirect('Recurso:consultar_serviços')

def omitir_serviços(request, omitirid):
    omit = get_object_or_404(Recurso_estado, id = omitirid)
    serviços = Serviço.objects.filter(recursoid__estado = omit)
    return render(request, "consultar_serviços.html", {'serviços': serviços,
                                                    'tipos': Recurso_estado.objects.all()})
    
def alterar_serviços(request, alterarid):
    error = "Serviço já existe"
    errorState = False
    recurso_change = Recurso.objects.get(pk = alterarid)
    r_form = recursos_form(request.POST or None, instance=recurso_change)
    if r_form.is_valid():
        r_form.save()
        return redirect('Recurso:consultar_serviços')
    return render(request, "alterar_serviços.html", {'recurso_change': recurso_change, 'r_form':r_form})

#======================================================================================================================================================

def consultar_equipamentos(request):
	return render(request, "consultar_equipamentos.html", {'equipamentos' : Equipamento.objects.all, 'tipos': Recurso_estado.objects.all()})

def adicionar_equipamentos(request):
    submitted = False
    error = "Equipamento já existe"
    errorState = False
    if request.method == "POST":
        r_form = recursos_form(request.POST)
        if r_form.is_valid():
            if Recurso.objects.filter(nome = r_form.data['nome']).exists():
                errorState = True
                return render(request, "adicionar_equipamentos.html", {'r_form':r_form, 'submitted':submitted, 'error':error, 'errorState':errorState})
            else:
                new_rid = r_form.save()
                new_serviço = Equipamento(recursoid = new_rid)
                new_serviço.save()
            return HttpResponseRedirect('/Recurso/consultar_equipamentos?submitted=True')
    else:
        r_form = recursos_form()
        if 'submitted' in request.GET:
            submitted = True
    return render(request, "adicionar_equipamentos.html", {'r_form':r_form, 'submitted':submitted})

def cancelar_equipamentos(request, removeid):
    Equipamento.objects.get(pk = removeid).delete()
    return redirect('Recurso:consultar_equipamentos')

def omitir_equipamentos(request, omitirid):
    omit = get_object_or_404(Recurso_estado, id = omitirid)
    equipamentos = Equipamento.objects.filter(recursoid__estado = omit)
    return render(request, "consultar_equipamentos.html", {'equipamentos': equipamentos,
                                                            'tipos': Recurso_estado.objects.all()})
    
def alterar_equipamentos(request, alterarid):
    error = "Equipamento já existe"
    errorState = False
    recurso_change = Recurso.objects.get(pk = alterarid)
    r_form = recursos_form(request.POST or None, instance=recurso_change)
    if r_form.is_valid():
        r_form.save()
        return redirect('Recurso:consultar_equipamentos')
    return render(request, "alterar_equipamentos.html", {'recurso_change': recurso_change, 'r_form':r_form})

Recurso/templates/adicionar_equipamentos.html
{% extends 'app.html' %}

{% block title %}- Adicionar Equipamento {% endblock title %}

{% block content %}
{% load static %}
<div class="center">
    <form action="" method="POST">
        <h1>Adicione um equipamento</h1>
        {% csrf_token %}

        {% if errorState == True %}
          {{ error }}
        {% endif %}

        <div class="fieldWrapper" >
          <label for="{{ form.nome.id_nome }}">Nome:</label>
          <br>
          {{ r_form.nome }}
      </div>
      <div class="fieldWrapper">
          <label for="{{ r_form.estado.id_estado }}">Estado:</label>
          <br>
          {{ r_form.estado }}
      </div>
      <br>
        <input type="submit" value="submit" class="btn btn-primary"></input>

        <a href="{% url 'Recurso:consultar_equipamentos' %}"><button type="button" class="btn btn-primary">Voltar</button></a>
  </form>
</div>

{% endblock content %}

Recurso/templates/adicionar_salas.html
{% extends 'app.html' %}

{% block title %}- Adicionar Sala {% endblock title %}

{% block content %}
{% load static %}
<div class="center">
    <form action="" method="POST">
        <h1>Adicione uma Sala</h1>
        {% csrf_token %}

        {% if errorState == True %}
          {{ error }}
        {% endif %}
          <div class="fieldWrapper" >
              <label for="{{ form.nome.id_nome }}">Nome:</label>
              <br>
              {{ r_form.nome }}
          </div>
          <div class="fieldWrapper">
              <label for="{{ r_form.estado.id_estado }}">Estado:</label>
              <br>
              {{ r_form.estado }}
          </div>
          <div class="fieldWrapper">
              <label for="{{ form.edificiosid.id_edificioid }}">Edificio:</label>
              <br>
              {{ s_form.edificioid }}
          </div>
          <div class="fieldWrapper">
              <label for="{{ form.lugares.id_lugares }}">Lugares:</label>
              <br>
              {{ s_form.lugares }}
          <br><br>
            <input type="submit" value="submit" class="btn btn-primary"></input>

            <a href="{% url 'Recurso:consultar_salas' %}"><button type="button" class="btn btn-primary">Voltar</button></a>
            <br><br>
      </div>
    </form>
</div>
{% endblock content %}

Recurso/templates/adicionar_serviços.html
{% extends 'app.html' %}

{% block title %}- Adicionar Serviço {% endblock title %}

{% block content %}
{% load static %}
<div class="center">
  <form action="" method="POST">
      <h1>Adicione um serviço</h1>
      {% csrf_token %}

      {% if errorState == True %}
        {{ error }}
      {% endif %}

      <div class="fieldWrapper" >
        <label for="{{ form.nome.id_nome }}">Nome:</label>
        <br>
        {{ r_form.nome }}
    </div>
    <div class="fieldWrapper">
        <label for="{{ r_form.estado.id_estado }}">Estado:</label>
        <br>
        {{ r_form.estado }}
    </div>
    <br>
      <input type="submit" value="submit" class="btn btn-primary"></input>

      <a href="{% url 'Recurso:consultar_serviços' %}"><button type="button" class="btn btn-primary">Voltar</button></a>
</form>
</div>

{% endblock content %}

Recurso/templates/consultar_equipamentos.html
{% extends 'app.html' %}

{% block title %}- Consultar Equipamentos {% endblock title %}

{% block content %}
{% load static %}
<div class="center">
  <h1>Consultar Equipamentos</h1>
</div>
  <br><br>
  <div class="dropdown container-fluid">
  <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown">
    Filtrar Equipamentos
  </button>
  <div class="dropdown-menu container-fluid">
    <a class="dropdown-item" href="{% url 'Recurso:consultar_equipamentos' %}">All</a>
    {% for t in tipos %}
      <br><a class="dropdown-item" href="{% url 'Recurso:omitir_equipamentos_view' t.id %}">{{t.Estado}}</a>
    {% endfor %}
  </div>
</div>
<a href="{% url 'Recurso:adicionar_equipamentos_view' %}">
  <button type="button" class="btn btn-primary">Adicione um equipamento</button>
</a>

<br><br>
  <table class="table" style="width:100%">
    <tr>
      <th>Equipamentos</th>
      <th>Estado</th>
      <th>Opções</th>
    </tr>
    {% for e in equipamentos %}
    <tr>
      <td>{{e.recursoid.nome}}</td>
      <td>{{e.recursoid.estado}}</td>
      <td>
        <a href="{% url 'Recurso:alterar_equipamentos_view' e.recursoid.id %}">
          <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pencil" viewBox="0 0 16 16">
            <path d="M12.146.146a.5.5 0 0 1 .708 0l3 3a.5.5 0 0 1 0 .708l-10 10a.5.5 0 0 1-.168.11l-5 2a.5.5 0 0 1-.65-.65l2-5a.5.5 0 0 1 .11-.168l10-10zM11.207 2.5 13.5 4.793 14.793 3.5 12.5 1.207 11.207 2.5zm1.586 3L10.5 3.207 4 9.707V10h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.293l6.5-6.5zm-9.761 5.175-.106.106-1.528 3.821 3.821-1.528.106-.106A.5.5 0 0 1 5 12.5V12h-.5a.5.5 0 0 1-.5-.5V11h-.5a.5.5 0 0 1-.468-.325z"/>
          </svg>
        </a>
        <a> | </a>
        <a href="{% url 'Recurso:remover_equipamentos_view' e.recursoid.id %}" onclick="clicked(event)">
          <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash" viewBox="0 0 16 16">
            <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z"/>
            <path fill-rule="evenodd" d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z"/>
          </svg>
        </a>
      </td>
    </tr>
    {% endfor %}
  </table>

  <script>
    function clicked(e)
    {
        if(!confirm('Tem a certeza que pretende eliminar este equipamento?')) {
            e.preventDefault();
        }
    }
  </script>
{% endblock content %}

Recurso/templates/consultar_salas.html
{% extends 'app.html' %}

{% block title %}- Consultar Salas {% endblock title %}

{% block content %}
{% load static %}
<div class="center">
  <h1>Consultar Salas</h1>
</div>
  <br><br>
  <div class="dropdown container-fluid">
    <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown">
      Filtrar Salas
    </button>
    <div class="dropdown-menu container-fluid">
      <a class="dropdown-item" href="{% url 'Recurso:consultar_salas' %}">All</a>
      {% for e in edificios %}
        <br><a class="dropdown-item" href="{% url 'Recurso:omitir_salas_view' e.id %}">{{e.nome}}</a>
      {% endfor %}
    </div>
  </div>
  <a href="{% url 'Recurso:adicionar_salas_view' %}">
    <button type="button" class="btn btn-primary">Adicione uma sala</button>
  </a>
  <br><br>
  <table class="table" style="width:100%">
    <tr>
      <th>Campus</th>
      <th>Edificio</th>
      <th>Sala</th>
      <th>Lugares</th>
      <th>Opções</th>
    </tr>
    {% for s in salas %}
    <tr>
      <td>{{s.edificioid.campusid.nome}}</td>
      <td>{{s.edificioid.nome}}</td>
      <td>{{s.recursoid.nome}}</td>
      <td>{{s.lugares}}</td>
      <td>
        <a href="{% url 'Recurso:alterar_salas_view' s.recursoid.id %}" >
          <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pencil" viewBox="0 0 16 16">
          <path d="M12.146.146a.5.5 0 0 1 .708 0l3 3a.5.5 0 0 1 0 .708l-10 10a.5.5 0 0 1-.168.11l-5 2a.5.5 0 0 1-.65-.65l2-5a.5.5 0 0 1 .11-.168l10-10zM11.207 2.5 13.5 4.793 14.793 3.5 12.5 1.207 11.207 2.5zm1.586 3L10.5 3.207 4 9.707V10h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.293l6.5-6.5zm-9.761 5.175-.106.106-1.528 3.821 3.821-1.528.106-.106A.5.5 0 0 1 5 12.5V12h-.5a.5.5 0 0 1-.5-.5V11h-.5a.5.5 0 0 1-.468-.325z"/>
          </svg>
        </a>

        <a> | </a>
        <a href="{% url 'Recurso:remover_salas_view' s.recursoid.id %}" onclick="clicked(event)">
          <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash" viewBox="0 0 16 16">
            <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z"/>
            <path fill-rule="evenodd" d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z"/>
          </svg>
        </a>
      </td>
    </tr>
    {% endfor %}
  </table>
  <script>
    function clicked(e)
    {
        if(!confirm('Tem a certeza que pretende eliminar esta sala?')) {
            e.preventDefault();
        }
    }
  </script>
{% endblock content %}

Recurso/templates/consultar_serviços.html
{% extends 'app.html' %}

{% block title %}- Consultar Serviços {% endblock title %}

{% block content %}
{% load static %}
<div class="center">
  <h1>Consultar Serviços</h1>
</div>
  <br><br>
  <div class="dropdown container-fluid">
  <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown">
    Filtrar Serviços
  </button>
  <div class="dropdown-menu container-fluid">
    <a class="dropdown-item" href="{% url 'Recurso:consultar_serviços' %}">All</a>
    {% for t in tipos %}
      <br><a class="dropdown-item" href="{% url 'Recurso:omitir_serviços_view' t.id %}">{{t.Estado}}</a>
    {% endfor %}
  </div>
</div>
<a href="{% url 'Recurso:adicionar_serviços_view' %}">
  <button type="button" class="btn btn-primary">Adicione um serviço</button>
</a>
<br><br>
  <table class="table" style="width:100%">
    <tr>
      <th>Serviços</th>
      <th>Estado</th>
      <th>Opções</th>
    </tr>
    {% for s in serviços %}
    <tr>
      <td>{{s.recursoid.nome}}</td>
      <td>{{s.recursoid.estado}}</td>
      <td>
        <a href="{% url 'Recurso:alterar_serviços_view' s.recursoid.id %}">
          <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pencil" viewBox="0 0 16 16">
            <path d="M12.146.146a.5.5 0 0 1 .708 0l3 3a.5.5 0 0 1 0 .708l-10 10a.5.5 0 0 1-.168.11l-5 2a.5.5 0 0 1-.65-.65l2-5a.5.5 0 0 1 .11-.168l10-10zM11.207 2.5 13.5 4.793 14.793 3.5 12.5 1.207 11.207 2.5zm1.586 3L10.5 3.207 4 9.707V10h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.293l6.5-6.5zm-9.761 5.175-.106.106-1.528 3.821 3.821-1.528.106-.106A.5.5 0 0 1 5 12.5V12h-.5a.5.5 0 0 1-.5-.5V11h-.5a.5.5 0 0 1-.468-.325z"/>
          </svg>
        </a>
        <a> | </a>
        <a href="{% url 'Recurso:remover_serviços_view' s.recursoid.id %}" onclick="clicked(event)">
          <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash" viewBox="0 0 16 16">
            <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z"/>
            <path fill-rule="evenodd" d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z"/>
          </svg>
        </a>
      </td>
    </tr>
    {% endfor %}
  </table>

  <script>
    function clicked(e)
    {
        if(!confirm('Tem a certeza que pretende eliminar esta serviço?')) {
            e.preventDefault();
        }
    }
  </script>
  
{% endblock content %}